twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
                 #,'widgets/data_list.html.twig']
    paths:
        '%kernel.project_dir%/public/css': styles
        '%kernel.project_dir%/public/images': images
    globals:
        photos_directory: '%app.photos%'
        entityFaker: '@App\Service\EntityFakerService'

when@test:
    twig:
        strict_variables: true
